= JEE passe à la fondation Eclipse
:published_at: 2017-10-04
:hp-tags: JEE, Fondation Eclipse
:toc: macro
:toclevels: 3
:lb: pass:[<br> +]
:imagesdir: ./images
:icons: font
:source-highlighter: highlightjs

// toc::[]

*JEE passe à la fondation Eclipse* : https://www.infoq.com/fr/news/2017/09/jee-gouvernance-fondationeclipse +
L'annonce était attendue depuis quelques temps maintenant, et la confirmation vient de tomber. +
Elle est à rapprocher de la lenteur des évolutions de la spécification, en effet, quand on regarde *le contenu du tout récent JEE 8* (https://jcp.org/en/jsr/detail?id=366[JSR 366]), on se rend qu'il est bien vide par rapport aux précédentes versions. C'est finalement presque un "non-évènement".

A ce sujet, je vous invite à écouter *l'intervention d'Antonio (GONCALVES)* dans https://lescastcodeurs.com/2017/09/04/lcc-176-le-paradoxe-de-la-fondation/[l'épisode 176 des Cast Codeurs]. Pour rappel, Antonio est membre de https://www.jcp.org/en/jsr/detail?id=366[*l'Expert Group JEE*], il est donc parfaitement au courant du sujet. +
Même si de grands groupes au JCP voient la chose positivement, et ont annoncé leur soutien à l'implémentation de la spécification (ce qui est également le cas d'Oracle), nous sommes en droit de *nous poser des questions sur la vitesse d'évolution de la plateforme à l'avenir*. +
Ce passage à la fondation Eclipse va-t-il enfin lui redonner le "coup de boost" que beaucoup attendent, où l'absence d'équipe de développement dédiée va-t-il l'enterrer ? +
